### ISSUE TITLE
Circuit Diagram has stopped working

### ISSUE THREAD

**Issue by mrpengilley** [circuitdiagram/circuitdiagram#1]
When I try and open the new stable version of Circuit Diagram I receive the following message:

"Circuit Diagram has stopped working
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."

Do you know what is happening here?

The Beta version was working fine no problems.

**Comment by SamuelFisher** [comment]
Could you post a copy of the error log to help find the problem? You can normally find it at:

`C:\Users\Username\AppData\Roaming\Circuit Diagram\ErrorLog.txt`

Thanks

**Comment by julienboriasse** [comment]
Here is mine:

System.IO.FileLoadException: Could not load file or assembly 'cdlibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=18fa230cbe445e9d' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'cdlibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=18fa230cbe445e9d'
   at CircuitDiagram.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

=== Pre-bind state information ===
LOG: DisplayName = cdlibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=18fa230cbe445e9d
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Circuit Diagram/
LOG: Initial PrivatePath = NULL

# Calling assembly : Circuit Diagram, Version=3.1.0.3, Culture=neutral, PublicKeyToken=null.

LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: cdlibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=18fa230cbe445e9d
LOG: Attempting download of new URL file:///C:/Program Files/Circuit Diagram/cdlibrary.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
